### ISSUE TITLE
请教这种数据该如何转换成json?

### ISSUE THREAD

**Issue by mrzhangxing** [childe/hangout#104]
{"info":"-IfName=GigabitEthernet2\/0\/26-MACAddr=28d2-447b-3efa-VLANID=518-Username=zhangsan;"}

key字段如下：
-IfName=
-MACAddr=
-VLANID=
-Username

**Comment by childe** [comment]
用Grok Filter:

^-IfName=(?<IfName>[^-]+)-MACAddr=(?<MACAddr>[^=]+)-VLANID=(?<VLANID>[^=]+)-Username=(?<Username>[^=]+)$

**Comment by mrzhangxing** [comment]
我没有太理解，麻烦再指教下哈
**源数据是：**
{"@timestamp":"2017-12-05T09:46:54.136Z","info":"Dec  1 09:54:25 2017 TCA5_LAN_AccS5130_F7_1 %%10DOT1X\/6\/DOT1X_LOGIN_FAILURE: -DevIP=10.252.0.1-Slot=2; -IfName=GigabitEthernet2\/0\/26-MACAddr=28d2-447b-3efa-VLANID=518-Username=zhangsan; User failed 802.1X authentication."

**我拆解info是这么做的：**
    - Grok:
        src: message
        match:
          - '^(?<date>\S+\s*\S+ \S+ \S+) (?<tmp1>\S+) (?<tmp2>\S+:) (?<IPS>-DevIP\S+) (?<info>\S+) (?<msg>.*)'
**通过上述得出来的结果是：**
{"date":""Dec  1 09:54:25 2017",
"IPS":"-DevIP=10.252.0.71-Slot=2;",
 "info":"-IfName=GigabitEthernet2\/0\/26-MACAddr=28d2-447b-3efa-VLANID=518-Username=zhangsan;"
....
}

**接下来我的想法是：**
("IPS":"-DevIP=10.252.0.71-Slot=2;"),将IPS按照"-分割，取出来后再"="切割,这样能得到DevIP和Slot的格式，写入ES
    - Add:
       fields:
         target1: '<#assign a=IPS?split("-")>${a[1]}'
         target2: '<#assign a=IPS?split("-")>${a[2]}'
       if:
         - '<#if IPS??>true</#if>'


但是后面的info这里面就不知道怎么做了，不太熟悉grok语法，这样的做法不知道对与否，麻烦再次协助哈

**Comment by childe** [comment]
```
- Grok:
    src: info
    match:
        - '^-IfName=(?[^-]+)-MACAddr=(?[^=]+)-VLANID=(?[^=]+)-Username=(?[^=]+)$'
```

直接用Grok会好一些, 清晰明了. 用Add一个个添加看着比较啰嗦.

PS, 你写的那个Grok好像没有用, 因为里面并没有message字段. 关于Grok语法, 可以参考
  https://github.com/kkos/oniguruma/blob/master/doc/RE

**Comment by mrzhangxing** [comment]
我直接将上述的grok复制的我这里，就报语法错误，然后退出了
```
Hangout  Version:0.3.0  Copyright @Ctrip   Author : childe@github, gnuhpc@github
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
        at com.ctrip.ops.sysdev.utils.Utils.lambda$null$0(Utils.java:39)
        at java.util.Iterator.forEachRemaining(Iterator.java:116)
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
        at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
        at com.ctrip.ops.sysdev.utils.Utils.lambda$createFilterProcessors$1(Utils.java:23)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
        at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
        at com.ctrip.ops.sysdev.utils.Utils.createFilterProcessors(Utils.java:22)
        at com.ctrip.ops.sysdev.baseplugin.BaseInput.createFilterProcessors(BaseInput.java:67)
        at com.ctrip.ops.sysdev.inputs.Kafka$ConsumerThread.<init>(Kafka.java:109)
        at com.ctrip.ops.sysdev.inputs.Kafka.lambda$null$3(Kafka.java:96)
        at java.util.ArrayList.forEach(ArrayList.java:1249)
        at com.ctrip.ops.sysdev.inputs.Kafka.lambda$emit$4(Kafka.java:96)
        at java.util.HashMap$EntrySet.forEach(HashMap.java:1035)
        at com.ctrip.ops.sysdev.inputs.Kafka.emit(Kafka.java:93)
        at com.ctrip.ops.sysdev.core.Main.lambda$null$2(Main.java:108)
        at java.util.LinkedHashMap.forEach(LinkedHashMap.java:676)
        at com.ctrip.ops.sysdev.core.Main.lambda$main$3(Main.java:85)
        at java.util.ArrayList.forEach(ArrayList.java:1249)
        at com.ctrip.ops.sysdev.core.Main.main(Main.java:83)
Caused by: org.joni.exception.SyntaxException: undefined group option
        at org.joni.ScannerSupport.newSyntaxException(ScannerSupport.java:166)
        at org.joni.Parser.parseEnclose(Parser.java:618)
        at org.joni.Parser.parseExp(Parser.java:716)
        at org.joni.Parser.parseBranch(Parser.java:1078)
        at org.joni.Parser.parseSubExp(Parser.java:1095)
        at org.joni.Parser.parseRegexp(Parser.java:1128)
        at org.joni.Parser.parse(Parser.java:65)
        at org.joni.Analyser.compile(Analyser.java:80)
        at org.joni.Regex.<init>(Regex.java:159)
        at org.joni.Regex.<init>(Regex.java:136)
        at org.joni.Regex.<init>(Regex.java:122)
        at com.ctrip.ops.sysdev.filters.Grok.prepare(Grok.java:173)
        at com.ctrip.ops.sysdev.baseplugin.BaseFilter.<init>(BaseFilter.java:76)
        at com.ctrip.ops.sysdev.filters.Grok.<init>(Grok.java:31)
        ... 24 more
```

**Comment by childe** [comment]
@mrzhangxing 抱歉, 文本贴过来, 被格式化之后, 显示的不对了, 我没注意到. 再贴一次.
```
- Grok:
    src: info
    match:
        - '^-IfName=(?<IfName>[^-]+)-MACAddr=(?<MACAddr>[^=]+)-VLANID=(?<VLANID>[^=]+)-Username=(?<Username>[^=]+)'
```

PS: 最前面的`^`和最后的`$`你看情况要不要加.

**Comment by mrzhangxing** [comment]
@childe 已解决，之前不熟悉这种用法，赞。jia哥
