### ISSUE TITLE
Newkafka: java.util.ArrayList cannot be cast to java.util.Map

### ISSUE THREAD

**Issue by mrzhangxing** [childe/hangout#133]
近期kafka那边用了1.0.0.1版本了，我在用Newkafka这个配置的时候，执行就报错后退出
kafka的服务器上看到版本
kafka_2.11-1.0.0.1.jar
kafka-tools-1.0.0.jar

hangout配置
```
- NewKafka:
    topic:
        hdp_test: 2
    type: nginx
    consumer_settings:
        bootstrap.servers: 192.1678.1.1:9092
        value.deserializer: org.apache.kafka.common.serialization.StringDeserializer
        key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
        group.id: hangout_hdp_test
        client.id: hdp_rsyslog



- Stdout: {}
```

报错信息：
```
Hangout  Version:0.3.0  Copyright @Ctrip   Author : childe@github, gnuhpc@github
java.lang.ClassCastException: java.util.ArrayList cannot be cast to java.util.Map
        at com.ctrip.ops.sysdev.config.HangoutConfig.parse(HangoutConfig.java:31)
        at com.ctrip.ops.sysdev.core.Main.main(Main.java:25)
```

默认的zip下载解压后的报错，后来我将kafka服务器kafka_2.11-1.0.0.1.jar、kafka-tools-1.0.0.jar替换默认hangout的jar不行，我又去官网下载替换对应的jar也不行

**Comment by mrzhangxing** [comment]
啊，犯低级错了，现在正常了。现在kafka和kafka-clients用到hangout自带的0.9版本才正常，用和kafka一样的版本却不行；留个记录，愿其他同学遇到直接跳过这个小坑

报错：Error registering AppInfo mbean

**Comment by childe** [comment]
嗯, 谢谢. 这个有可能, 因为截至目前更高版本的kafka server还兼容0.9版本的kafka client. 但使用更高版本的kafka client lib, 可能和hangout中的kafka消费代码已经不兼容了.
