### ISSUE TITLE
从kafka拉数据到es，启动的时候报错老是： bin/hangout -f test.yml 

### ISSUE THREAD

**Issue by baiyq152** [childe/hangout#17]
Exception in thread "main" java.lang.NullPointerException
        at scala.collection.convert.Wrappers$JMapWrapperLike$$anon$2.<init>(Wrappers.scala:265)
        at scala.collection.convert.Wrappers$JMapWrapperLike$class.iterator(Wrappers.scala:264)
        at scala.collection.convert.Wrappers$JMapWrapper.iterator(Wrappers.scala:275)
        at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
        at scala.collection.TraversableOnce$class.foldLeft(TraversableOnce.scala:144)
        at scala.collection.AbstractTraversable.foldLeft(Traversable.scala:105)
        at scala.collection.TraversableOnce$class.$div$colon(TraversableOnce.scala:138)
        at scala.collection.AbstractTraversable.$div$colon(Traversable.scala:105)
        at scala.collection.immutable.MapLike$class.$plus$plus(MapLike.scala:87)
        at scala.collection.immutable.AbstractMap.$plus$plus(Map.scala:187)
        at kafka.javaapi.consumer.ZookeeperConsumerConnector.createMessageStreams(ZookeeperConsumerConnector.scala:83)
        at kafka.javaapi.consumer.ZookeeperConsumerConnector.createMessageStreams(ZookeeperConsumerConnector.scala:97)
        at com.ctrip.ops.sysdev.inputs.Kafka.emit(Kafka.java:128)
        at com.ctrip.ops.sysdev.Main.main(Main.java:109)

我的配置
inputs:
    - Kafka:
        codec: json
        topic: 
        wiseweb_crawler_webpage: 4
        consumer_settings:
          group.id: hangouts
         # socket.receive.buffer.bytes:"1048576"
         # fetch.message.max.bytes:"1048576"
          zookeeper.connect: 10.165.65.14:2181,10.171.100.247:2181,10.251.5.35:2181
          auto.commit.interval.ms: "5000"
这是输入

感谢

**Comment by childe** [comment]
你使用的zk, kafka, hangout版本是什么?

**Comment by baiyq152** [comment]
好了，我之前用hadoop用户启动老是报错，今天用root启动了下，可以了，数据到es了，谢谢
