### ISSUE TITLE
从kafka取消息，启动就报错

### ISSUE THREAD

**Issue by william-yang** [childe/hangout#32]
hangout是下载的release版本：hangout-0.1.8.2
kafka：0.8.2.2
hangout的配置文件：

inputs:
    - Kafka:
        codec: plain
        topic:
          loglib.app.json: 2
        consumer_settings:
          group.id: hangout
          zookeeper.connect: 1.2.3.4/kafka/uat
          auto.commit.interval.ms: "5000"
          socket.receive.buffer.bytes: "10485760"
         # fetch.message.max.bytes: "10485760"
         # num.consumer.fetchers: "2"

outputs:
    - Stdout: {}

启动命令:./bin/hangout -f config/test.yml  -l log/test.log
启动后一直在报错：
2016-12-21 19:22:10,642 WARN kafka.utils.Logging$class ConsumerFetcherThread-hangout_AA-1482319320793-3d1d64a9-0-47 [ConsumerFetcherThread-hangout_AA-1482319320793-3d1d64a9-0-47], Error in fetch kafka.consumer.ConsumerFetcherThread$FetchRequest@23af0b3c. Possible cause: java.nio.BufferUnderflowException
2016-12-21 19:22:10,916 WARN kafka.utils.Logging$class ConsumerFetcherThread-hangout_AA-1482319320793-3d1d64a9-0-45 [ConsumerFetcherThread-hangout_AA-1482319320793-3d1d64a9-0-45], Error in fetch kafka.consumer.ConsumerFetcherThread$FetchRequest@2f9dc6f7. Possible cause: java.nio.BufferUnderflowException

hangout启动给的5G
HO_HEAP_SIZE="${HO_HEAP_SIZE:=5000m}"

帮忙看下哪里配置不对，多谢

**Comment by childe** [comment]
把vender文件夹下面的kafka的包, 换成和你的kafka匹配的. 试试看还有这个问题不.

**Comment by william-yang** [comment]
已换成kafka匹配的包，但是报错；是不是JDK版本不合适？我用的版本是java version "1.7.0_45"

Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:5
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImp
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at com.ctrip.ops.sysdev.Main.main(Main.java:107)
Caused by: java.lang.NoSuchMethodError: scala.Predef$.ArrowAssoc(Ljava/lang/Object;)Ljava/lang/Object
	at kafka.consumer.ZookeeperConsumerConnector.<init>(ZookeeperConsumerConnector.scala:107)
	at kafka.javaapi.consumer.ZookeeperConsumerConnector.<init>(ZookeeperConsumerConnector.scala:
	at kafka.javaapi.consumer.ZookeeperConsumerConnector.<init>(ZookeeperConsumerConnector.scala:
	at kafka.consumer.Consumer$.createJavaConsumerConnector(ConsumerConnector.scala:105)
	at kafka.consumer.Consumer.createJavaConsumerConnector(ConsumerConnector.scala)
	at com.ctrip.ops.sysdev.inputs.Kafka.prepare(Kafka.java:115)
	at com.ctrip.ops.sysdev.inputs.BaseInput.<init>(BaseInput.java:105)
	at com.ctrip.ops.sysdev.inputs.Kafka.<init>(Kafka.java:96)
	... 5 more

**Comment by childe** [comment]
我看了一下官方的文档, http://kafka.apache.org/082/documentation.html#highlevelconsumerapi  以及给的链接 https://cwiki.apache.org/confluence/display/KAFKA/Consumer+Group+Example , 看起来在"at com.ctrip.ops.sysdev.inputs.Kafka.prepare(Kafka.java:115)" 这行代码下, 不应该报 "Caused by: java.lang.NoSuchMethodError: " .
看一下你用的jar包? 是哪一个?

**Comment by william-yang** [comment]
我用的jar包是直接从kafka服务器上取的kafka_2.11-0.8.2.2.jar ；kafka-clients-0.8.2.2.jar；
或者您能帮忙提供jar的下载地址吗？

**Comment by william-yang** [comment]
可以读取了，用的jar包是kafka_2.10-0.8.2.2.jar

**Comment by jwcn** [comment]
@william-yang 您好,请问您是怎么解决的, 我也遇到这个问题了, 我的 kafka 和 zookeeper 的包都是从 kafka 机器上拷贝过来的, 报错和您相同
