### ISSUE TITLE
hangout-0.1.8.2-ES2.3.5读取kafka消息报错

### ISSUE THREAD

**Issue by Baz2013** [childe/hangout#48]
hangout：hangout-0.1.8.2-ES2.3.5
kafka: 0.8.2.0
zookeeper:3.3.5

配置文件：
inputs:
    - Kafka:
        codec: json
        encoding: UTF8 # defaut UTF8
        topic: 
          log_billing: 2
        consumer_settings:
          group.id: hangout
          zookeeper.connect: xx.xx.xx.xx:21810
          auto.commit.interval.ms: "1000"
outputs:
    - Stdout: {}

读取不到kafka中的消息，在日志中报如下错误
2017-01-20 11:26:39,151 WARN kafka.utils.Logging$class ConsumerFetcherThread-hangout_resourcepool-0231-jkdd01-1484882793828-16b4fdc5-0-2 [ConsumerFetcherThread-hangout_resourcepool-0231-jkdd01-1484882793828-16b4fdc5-0-2], Error in fetch kafka.consumer.ConsumerFetcherThread$FetchRequest@1965eff6. Possible cause: java.lang.IllegalArgumentException

将vender下kafka相关的jar包换成我服务器上kafka目录下的jar包后，启动时报这样的错误：
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at com.ctrip.ops.sysdev.Main.main(Main.java:107)
Caused by: java.lang.NoClassDefFoundError: scala/reflect/ClassManifest
	at kafka.utils.Log4jController$.<init>(Log4jController.scala:29)
	at kafka.utils.Log4jController$.<clinit>(Log4jController.scala)
	at kafka.utils.Logging$class.$init$(Logging.scala:29)
	at kafka.utils.VerifiableProperties.<init>(VerifiableProperties.scala:26)
	at kafka.consumer.ConsumerConfig.<init>(ConsumerConfig.scala:94)
	at com.ctrip.ops.sysdev.inputs.Kafka.prepare(Kafka.java:114)
	at com.ctrip.ops.sysdev.inputs.BaseInput.<init>(BaseInput.java:105)
	at com.ctrip.ops.sysdev.inputs.Kafka.<init>(Kafka.java:96)
	... 5 more
Caused by: java.lang.ClassNotFoundException: scala.reflect.ClassManifest
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)

**Comment by childe** [comment]
你需要的应该是这一个
http://mvnrepository.com/artifact/org.apache.kafka/kafka_2.10/0.8.2.0

**Comment by Baz2013** [comment]
非常感谢，用这个jar就能正常读取了

**Comment by 442943738** [comment]
这个用哪个jar包取决于什么？
hangout：hangout-0.2.1
kafka: 2.9.1-0.8.2.2
zookeeper:3.4.6
同样的问题
