### ISSUE TITLE
设置index_type取字段值时,如果字段不存在,则出错

### ISSUE THREAD

**Issue by jwcn** [childe/hangout#69]
设置index_type取字段值时,如果消息中字段不存在,则出错, 能否兼容处理下, 字段不存在时取默认值,  或者取第二优先级的字段

配置如下:
```
outputs:
    - Elasticsearch:
        cluster: elasticsearch
        hosts:
          - 192.168.12.29
        index: '%{@index}'
        index_type: ${@type} # default logs
        #document_id: ${id} # defautt null, generated by es
        bulk_actions: 20000 #default 20000
        bulk_size: 15 # default 15 MB
        flush_interval: 10 # default 10 seconds
        concurrent_requests: 0 # default 0, concurrent_requests设置成大于0的数, 意思着多线程处理, 以我应用的经验,还有是一定OOM风险的,强烈建议设置为0
        #timezone: "Asia/Shanghai" # defaut UTC 时区. 只用于生成索引名字的字符串格式化
#        sniff: false #default true
```

数据示例:
```
[
            '@index' => 'jw',
           //  '@type' => 'jw_type4',  // 没有该字段时则出错
            'lion_k' => date('Y-m-d H:i:s'),
            'test_array' => [
                'k1' => 1,
                'k2' => 'aaa'
            ]
]
```

当没有 `@type` 字段时则报错

报错如下:

```
2017-05-03 10:53:11,337 ERROR freemarker.log._Log4jLoggerFactory$Log4jLogger pool-2-thread-7 Error executing FreeMarker template
FreeMarker template error:
The following has evaluated to null or missing:
==> @type  [in template "${@type}" at line 1, column 3]

----
Tip: If the failing expression is known to be legally refer to something that's sometimes null or missing, either specify a default value like myOptionalVar!myDefault, or use <#if myOptionalVar??>when-present<#else>when-missing</#if>. (These only cover the last step of the expression; to cover the whole expression, use parenthesis: (myOptionalVar.foo)!myDefault, (myOptionalVar.foo)??
----

----
FTL stack trace ("~" means nesting-related):
        - Failed at: ${@type}  [in template "${@type}" at line 1, column 1]
----

Java stack trace (for programmers):
----
freemarker.core.InvalidReferenceException: [... Exception message was already printed; see it above ...]
        at freemarker.core.InvalidReferenceException.getInstance(InvalidReferenceException.java:131)
        at freemarker.core.EvalUtil.coerceModelToString(EvalUtil.java:355)
        at freemarker.core.Expression.evalAndCoerceToString(Expression.java:82)
        at freemarker.core.DollarVariable.accept(DollarVariable.java:41)
        at freemarker.core.Environment.visit(Environment.java:324)
        at freemarker.core.Environment.process(Environment.java:302)
        at freemarker.template.Template.process(Template.java:323)
        at com.ctrip.ops.sysdev.render.FreeMarkerRender.render(FreeMarkerRender.java:34)
        at com.ctrip.ops.sysdev.outputs.Elasticsearch.emit(Elasticsearch.java:215)
        at com.ctrip.ops.sysdev.outputs.BaseOutput.process(BaseOutput.java:60)
        at com.ctrip.ops.sysdev.inputs.Kafka$Consumer.run(Kafka.java:77)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
2017-05-03 10:53:11,694 ERROR com.ctrip.ops.sysdev.render.FreeMarkerRender pool-2-thread-7 The following has evaluated to null or missing:
==> @type  [in template "${@type}" at line 1, column 3]

----
Tip: If the failing expression is known to be legally refer to something that's sometimes null or missing, either specify a default value like myOptionalVar!myDefault, or use <#if myOptionalVar??>when-present<#else>when-missing</#if>. (These only cover the last step of the expression; to cover the whole expression, use parenthesis: (myOptionalVar.foo)!myDefault, (myOptionalVar.foo)??
----

----
FTL stack trace ("~" means nesting-related):
        - Failed at: ${@type}  [in template "${@type}" at line 1, column 1]
----
2017-05-03 10:53:18,253 ERROR com.ctrip.ops.sysdev.outputs.Elasticsearch$1 elasticsearch[Rick Jones][bulk_processor][T#1] bulk has failed item which do NOT need to retry
2017-05-03 10:53:18,255 ERROR com.ctrip.ops.sysdev.outputs.Elasticsearch$1 elasticsearch[Rick Jones][bulk_processor][T#1] java.lang.IllegalArgumentException: Validation Failed: 1: mapping type is empty;
```

**Comment by childe** [comment]
${@type!'logs'}
