### ISSUE TITLE
hangout启动报错

### ISSUE THREAD

**Issue by 442943738** [childe/hangout#72]
hangout：hangout-0.2.1
kafka: 2.9.1-0.8.2.2
zookeeper:3.4.6
启动报错
2017-05-11 11:19:26,531 WARN kafka.utils.Logging$class ConsumerFetcherThread-hangout_node-1-1494472750245-ca30e025-0-0 [ConsumerFetcherThread-hangout_node-1-1494472750245-ca30e025-0-0], Error in fetch kafka.consumer.ConsumerFetcherThread$FetchRequest@7a608ee4. Possible cause: java.lang.IllegalArgumentException
2017-05-11 11:19:26,748 WARN kafka.utils.Logging$class ConsumerFetcherThread-hangout_node-1-1494472750245-ca30e025-0-0 [ConsumerFetcherThread-hangout_node-1-1494472750245-ca30e025-0-0], Error in fetch kafka.consumer.ConsumerFetcherThread$FetchRequest@2925b301. Possible cause: java.lang.IllegalArgumentException

该成自己的kafka 
[root@elk bin]# ./hangout -f ../conf/kaf-es.yml 
Hangout  Version:0.2.1  Copyright @Ctrip   Author : childe@github, gnuhpc@github
Exception in thread "main" java.lang.NoClassDefFoundError: scala/ScalaObject
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at com.ctrip.ops.sysdev.core.Main.lambda$null$0(Main.java:67)
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
	at com.ctrip.ops.sysdev.core.Main.lambda$main$1(Main.java:58)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at com.ctrip.ops.sysdev.core.Main.main(Main.java:56)
Caused by: java.lang.ClassNotFoundException: scala.ScalaObject
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 31 more

**Comment by childe** [comment]
http://mvnrepository.com/artifact/org.apache.kafka/kafka_2.9.1/0.8.2.2
用这个替换

**Comment by 442943738** [comment]
[root@node-1 libs]# ls |grep kafka
kafka_2.9.1-0.8.2.2.jar
kafka-clients-0.8.2.2.jar
[root@node-1 libs]# 
[root@node-1 libs]# cd ..
[root@node-1 hangout-0.2.1]# ./bin/hangout -f conf/
example.yml           kaf-es.yml            simpletest.yml        testeshttpoutput.yml  testkafkainput.yml    testkafkaoutput.yml   
[root@node-1 hangout-0.2.1]# ./bin/hangout -f conf/kaf-es.yml 
Hangout  Version:0.2.1  Copyright @Ctrip   Author : childe@github, gnuhpc@github
Exception in thread "main" java.lang.NoClassDefFoundError: scala/ScalaObject
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at com.ctrip.ops.sysdev.core.Main.lambda$null$0(Main.java:67)
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
	at com.ctrip.ops.sysdev.core.Main.lambda$main$1(Main.java:58)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at com.ctrip.ops.sysdev.core.Main.main(Main.java:56)
Caused by: java.lang.ClassNotFoundException: scala.ScalaObject
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 31 more
之前就用的这个，还是不行呢。
配置文件
inputs:
    - Kafka:
        codec: plain
        encoding: UTF8 # defaut UTF8
        topic:
          test: 2
        consumer_settings:
          group.id: hangout
          zookeeper.connect:x.x.x.x:2181,x.x.x.x:2181,x.x.x.x:2181
outputs:
    - Elasticsearch:
        cluster: elasticsearch
        hosts:
          - x.x.x.x
          - x.x.x.x
          -  x.x.x.x
        index_type: logs 
        bulk_actions: 20000 
        bulk_size: 15 
        flush_interval: 10
        concurrent_requests: 0

**Comment by childe** [comment]
https://mvnrepository.com/artifact/org.scala-lang/scala-library/2.9.1
应该是scala的版本也需要一致. 因为你的kafak是用的scala2.9.1的这个版本.
